language: python
services: mongodb
sudo: required
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install -r requirements-optional.txt
before_script:
  - python setup.py develop
  - ./install-mpi.sh openmpi
script: 
  - nosetests -v maggma
  - mpiexec -n 2  python $PWD/maggma/tests/mpi_test.py
notifications:
  email:
    recipients:
      - montoyjh@lbl.gov
      - kmathew@lbl.gov
    on_success: change
    on_failure: always
