site_name: Maggma Documentation
site_description: Documentation for Maggma, a files-to-API data pipeline for scientific applications
copyright: Built by The Materials Project

theme:
  name: 'material'


nav:
  - Home: "index.md"
  - Core Concepts: "concepts.md"

repo_url: https://github.com/materialsproject/maggma/
docs_dir: ./src/docs2
markdown_extensions:
  - codehilite
  - admonition
  - pymdownx.superfences
